### ISSUE TITLE
When Selvvir references caniuse.com, link to the page as well

### ISSUE THREAD

**Issue by oksushi** [hashcss/hashcss.com#31]
When requested, Selvvir will show browser support stats from caniuse.com. It would be handy to link to the page as well, to discover other information.

**Comment by AMcBain** [comment]
Resolved and deployed. https://bitbucket.org/AMcBain/selvvir/commits/6512a6a99fed69ecd931bee62572fdd9838f397e

**Comment by oksushi** [comment]
:+1:
